version: "3.8"

services:
  backend:
    build:
      context: ./music_generation
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
   
    